const col = [
    "linear-gradient(to top, #a8edea 0%, #fed6e3 100%)",
    "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    "linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)",
    // "linear-gradient(120deg, #f093fb 0%, #f5576c 100%)",
    "linear-gradient(-225deg, #E3FDF5 0%, #FFE6FA 100%)",
    // "linear-gradient(to top, #5ee7df 0%, #b490ca 100%)",
    "linear-gradient(to top, #d299c2 0%, #fef9d7 100%)",
    "linear-gradient(to top, #ebc0fd 0%, #d9ded8 100%)",
    // "linear-gradient(120deg, #f6d365 0%, #fda085 100%)",
    // "linear-gradient(to top, #96fbc4 0%, #f9f586 100%)",
    "linear-gradient(-225deg, #FFFEFF 0%, #D7FFFE 100%)",
    "linear-gradient(to top, #fff1eb 0%, #ace0f9 100%)",
    "linear-gradient(to top, #c1dfc4 0%, #deecdd 100%)",
    "linear-gradient(-20deg, #ddd6f3 0%, #faaca8 100%)",
];

const data = [
    {
        name: "Mausam",
        position: "Head",
        research_areas: [
            "Artificial Intelligence",
            "Natural Language Processing",
            "Machine Learning",
        ],
        address: [
            "Room 402, SIT Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "mausam[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6076",
        page: "https://www.cse.iitd.ac.in/~mausam/",
        image: "/faculty/mausam.jpg",
    },
    {
        name: "Manish Agarwal",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "molecular simulations",
            "enhancing efficiency of various codes",
            "HPC",
        ],
        address: [
            "Main Building, Computer Services Centre,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "zmanish[AT]cc.iitd.ac.in",
        phone: "+91-11-2659-7170",
        page: "https://web.iitd.ac.in/~zmanish/",
        image: "/faculty/manish.jpg",
    },
    {
        name: "Sumeet Agarwal",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Machine Learning",
            "Cognitive Science",
            // "Systems Biology",
            "Complex Networks",
            "Computational Linguistics",
            "Computational Social Science",
        ],
        address: [
            "Room No. 404, Block II, Department of Electrical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "sumeet[AT]iitd.ac.in",
        phone: "+91-11-2659-6159",
        page: "http://web.iitd.ac.in/~sumeet",
        image: "/faculty/sumeet.jpg",
    },
    {
        name: "Ankush Agrawal",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Applied Econometrics",
            "Development Economics",
            "India’s Official Statistics",
        ],
        address: [
            "Room 402G, Block II,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "ankush[AT]hss.iitd.ac.in",
        phone: "+91-11-2659-1371",
        page: "https://hss.iitd.ac.in/faculty/ankush-agrawal",
        image: "/faculty/ankush.jpg",
    },
    {
        name: "Prathosh A.P.",
        position: "Adjunct Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Vision and image processing",
            "Audio, speech and music analytics and learning (deep learning, sequential modelling and transfer learning)",
        ],
        address: [
            "Room II-114 (Block -II, Ground floor),",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "prathoshap[AT]ee.iitd.ac.in",
        phone: "+91-11-2659-1151",
        page: "https://sites.google.com/view/prathosh",
        image: "/faculty/prathosh.jpg",
    },
    {
        name: "Chetan Arora",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: ["Computer Vision", "Machine Learning"],
        address: [
            "Room 116, Khosla School of IT, Department of Computer Science and Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "chetan[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-1279",
        page: "https://www.cse.iitd.ac.in/~chetan/",
        image: "/faculty/chetan.jpg",
    },
    {
        name: "Amitabha Bagchi",
        position: "Associate Faculty",
        // position: "Professor",
        research_areas: [
            "Structural Properties of Networks",
            "Algorithms",
            "Data Structures",
        ],
        address: [
            "Room 203 SIT Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "bagchi[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6397",
        page: "https://www.cse.iitd.ac.in/~bagchi/",
        image: "/faculty/amitabha.jpg",
    },
    {
        name: "Sorav Bansal",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: ["Compilers", "Operating Systems"],
        address: [
            "Room 413 SIT Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "sbansal[AT]iitd.ac.in",
        phone: "+91-11-2659-6020",
        page: "http://www.cse.iitd.ac.in/~sbansal",
        image: "/faculty/sorav.jpg",
    },
    {
        name: "Srikanta Bedathur",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Data Management",
            "Knowledge Discovery and Data Mining",
            "Natural Language Processing",
        ],
        address: ["Bharti 423,", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "srikanta[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6010",
        page: "https://www.cse.iitd.ac.in/~srikanta/",
        image: "/faculty/srikanta.png",
    },
    {
        name: "Abhijnan Chakraborty",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Social Computing",
            "Information Retrieval",
            "Fairness in Machine Learning",
        ],
        address: ["Bharti 418,", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "abhijnan[AT]iitd.ac.in",
        phone: "+91-11-2659-XXXX",
        page: "https://www.cse.iitd.ac.in/~abhijnan/index.html",
        image: "/faculty/abhi.jpg",
    },
    {
        name: "Souvik Chakraborty",
        position: "Joint Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Deep learning",
            "Digital twin",
            // "Stochastic mechanics/dynamics",
            "Reliability analysis",
            "Design under uncertainty",
            "multi-scale systems",
            // "inverse problems",
        ],
        address: [
            "Room 342C, Block IV,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "souvik[AT]am.iitd.ac.in",
        phone: "+91-11-2659-8483",
        page: "https://www.csccm.in/home",
        image: "/faculty/souvik.png",
    },
    {
        name: "Niladri Chatterjee",
        imgPos: "top",
        position: "Joint Faculty",
        // position: "Professor",
        research_areas: [
            "Machine Translation",
            "Artificial Intelligence",
            "Reasoning",
            "Statistical Modelling",
            "Semantic Web",
        ],
        address: [
            "Room: MZ167, Department of Mathematics,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "niladri[AT]maths.iitd.ac.in",
        phone: "+91-11-2659-1490",
        page: "https://web.iitd.ac.in/~niladri/",
        image: "/faculty/niladri.png",
    },
    {
        name: "Arpan Chattopadhyay",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "IoT",
            // "Cyber-physical systems",
            "Next-generation wireless communication and networking",
            "Machine learning",
            "Reinforcement learning",
            // "Radar",
            "Statistical signal processing",
        ],
        address: [
            "Room 334, Block II, Department of Electrical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "arpanc[AT]ee.iitd.ac.in",
        phone: "+91-11-2659-1137",
        page: "https://sites.google.com/site/arpanchattop/home",
        image: "/faculty/arpanc.png",
    },
    {
        name: "Dinesh Garg",
        position: "Adjunct Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Algorithms and Theory",
            "Knowledge Discovery and Data Mining",
            "Operations Research",
            "Reasoning",
            "Machine Learning",
        ],
        address: [
            "Senior Researcher, AI Reasoning,",
            "India Research Laboratory, Bangalore, India",
        ],
        email: "garg.dinesh[AT]in.ibm.com",
        phone: "+91-880-009-6802",
        page: "https://researcher.watson.ibm.com/researcher/view.php?person=in-garg.dinesh",
        image: "/faculty/dinesh.jpg",
    },
    {
        name: "Arnob Ghosh",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Reinforcement Learning",
            "Game Theory",
            "Smart Grid",
            "Dynamical System",
            "Intelligent Control",
        ],
        address: [
            "Room No. 258, Block III, Mechanical Engineering Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "aghosh[AT]iitd.ac.in",
        phone: "+91-11-2659-8428",
        page: "https://sites.google.com/site/arnob008/",
        image: "/faculty/arnob.jpg",
    },
    {
        name: "Nitya Nand Gosvami",
        imgPos: "top",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Fundamental Mechanisms of Friction and Wear of Materials",
            // "Nanotribology of Engineering Materials and Industrial Lubricant Additives",
            // "Nanoscale in Situ Methods in Tribology, Surface Science & Engineering",
            "Failure Analysis of Materials",
            // "Development of Novel Scanning Probe Microscopy Technique",
            "Nanoscience and Nanotechnology",
            "Surface Science & Engineering",
        ],
        address: [
            "Room No: TX-200J, Block III, Dept. of Materials Science and Engineering",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "ngosvami[AT]iitd.ac.in",
        phone: "+91-11-2659-6414",
        page: "https://mse.iitd.ac.in/faculty-nitya.php",
        image: "/faculty/nitya.jpg",
    },
    {
        name: "Agam Gupta",
        // imgPos: "top",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Computational Social Science, and Networks",
            "Sharing Economy",
        ],
        address: ["DMS", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "agam[AT]iitd.ac.in",
        phone: "+91-11-2654-8406",
        page: "https://dms.iitd.ac.in/faculity_type/prof-agamgupta/",
        image: "/faculty/agam.jpg",
    },
    {
        name: "Jayadeva",
        // imgPos: "top",
        position: "Associate Faculty",
        // position: "Professor",
        research_areas: [
            "Machine Learning",
            "Neuromorphic Engineering",
            "Optimization",
        ],
        address: [
            "Room 218, Block II, Dept. of Electrical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: " jayadeva[AT]ee.iitd.ac.in",
        phone: "+91-11-2652-6821",
        page: "https://web.iitd.ac.in/~jayadeva/",
        image: "/faculty/jayadeva.jpg",
    },
    {
        name: "Arpan Kumar Kar",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Internet And Social Media",
            "Machine Learning Applications",
            "Data Science and Big Data",
            "Management of AI/ML Technology",
        ],
        address: [
            "Room 502, Vishwakarma Bhawan,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "arpankar[AT]iitd.ac.in",
        phone: "+91-11-2659-7320",
        page: "https://arpankar.com",
        image: "/faculty/arpan.jpg",
    },
    {
        name: "Hariprasad Kodamana",
        position: "Joint Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Graphs",
            "Spatiotemporal Analytics",
            "Anomaly Detection",
            "Optimization",
            "Reinforcement Learning",
        ],
        address: [
            "Room 286, Block II,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "kodamana[AT]iitd.ac.in",
        phone: "+91-11-2659-1024",
        page: "https://web.iitd.ac.in/~kodamana/",
        image: "/faculty/hariprasad.jpg",
    },
    {
        name: "N. M. Anoop Krishnan",
        position: "Joint Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Materials Modelling",
            "Data driven modelling and discovery of materials",
            "AI and ML for materials",
        ],
        address: [
            "Room 314, Block IV,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "krishnan[AT]iitd.ac.in",
        phone: "+91-11-2659-1223",
        page: "https://sites.google.com/site/nmakrishnaniitd/home/",
        image: "/faculty/anoop.jpg",
    },
    {
        name: "Sandeep Kumar",
        position: "Joint Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Optimization",
            "Signal Processing",
            "Machine Learning",
            "Graphical Models",
        ],
        address: [
            "Room 243, Block II, Dept. of Electrical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "ksandeep[AT]iitd.ac.in",
        phone: "+91-11-2659-5490",
        page: "https://sites.google.com/view/sandeepkr/home",
        image: "/faculty/sandeep.png",
    },
    {
        name: "Aparna Mehra",
        position: "Associate Faculty",
        // position: "Professor",
        research_areas: ["Optimization Theory"],
        address: [
            "Room: MZ151, Department of Mathematics,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "apmehra[AT]maths.iitd.ac.in",
        phone: "+91-11-2659-7106",
        page: "https://web.iitd.ac.in/~apmehra/",
        image: "/faculty/aparna.png",
    },
    {
        name: "Amit Mehndiratta",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Medical Image Processing (Algorithm Development & Analysis)",
            "Neuro-Assistive Technologies in Rehabilitation",
        ],
        address: [
            "Room No. 298, Block III, Centre for Biomedical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "amehndiratta[AT]cbme.iitd.ac.in",
        phone: "+91-11-2659-6230",
        page: "https://web.iitd.ac.in/~amehndiratta/",
        image: "/faculty/amit.jpg",
    },
    {
        name: "Preeti Ranjan Panda",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Energy-efficient Embedded Systems",
            "Cache Management and Memory Technologies",
            "Electronic Design Automation and Design Methodology",
        ],
        address: [
            "Room 202, Khosla School of IT, Department of Computer Science and Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "panda[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6030",
        page: "https://www.cse.iitd.ac.in/~panda/",
        image: "/faculty/preeti.jpg",
    },
    {
        name: "Kolin Paul",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Affordable HealthCare --- Science to Systems",
            "Hardware and Embedded Systems",
        ],
        address: [
            "Room 102, Khosla School of IT, Department of Computer Science and Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "kolin[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6033",
        page: "https://www.cse.iitd.ac.in/~kolin/Kolins_Web_Home/My_Home.html",
        image: "/faculty/kolin.jpg",
    },
    {
        name: "Rohan Paul",
        position: "Joint Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Robot Intelligence",
            "Embodied AI",
            "Sub: Learning, planning and human assistance",
        ],
        address: [
            "Room 414, Khosla School of IT, Department of Computer Science and Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "rohan[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-8435",
        page: "https://www.cse.iitd.ac.in/~rohanpaul",
        image: "/faculty/rohan.jpg",
    },
    {
        name: "Anurag Rathore",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Continuous Processing",
            "Analytical & Functional Characterization of Biosimilars",
            "Data Analytics",
        ],
        address: [
            "Department of Chemical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "arathore[AT]chemical.iitd.ac.in",
        phone: "+91-11-2659-1098",
        page: "http://www.biotechcmz.com/",
        image: "/faculty/anurag.jpg",
    },
    {
        name: "Maya Ramanath",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Database Systems and Information Retrieval",
            "Semantic Web Data Management",
            "Knowledge graph construction and applications",
        ],
        address: [
            "Room 214, SIT Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "ramanath[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6022",
        page: "https://www.cse.iitd.ac.in/~ramanath/",
        image: "/faculty/maya.jpg",
    },
    {
        name: "Manojkumar C. Ramteke",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "meta-heuristic algorithms",
            "machine learning",
            "novel computing methods",
        ],
        address: [
            "Room 311, Block I,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "mcramteke[AT]chemical.iitd.ac.in",
        phone: "+91-11-2659-1026",
        page: "https://web.iitd.ac.in/~mcramteke/Home.html",
        image: "/faculty/manoj.jpg",
    },
    {
        name: "Sayan Ranu",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Machine Learning and Data Mining for Graphs",
            "Spatio-temporal Data Analytics",
            "Bioinformatics",
        ],
        address: ["Bharti 421,", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "sayanranu[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6383",
        page: "https://www.cse.iitd.ac.in/~sayan/",
        image: "/faculty/sayan.jpg",
    },
    {
        name: "Sitikantha Roy",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Soft Robotics (Actuator, sensor, control)",
            "AI in Healthcare/ digital health",
            "Scientific Computation/Nonlinear Optimization",
            // "Bioinspired Engineering",
            "Biomechanics (Musculoskeletal/Brain/Cardiovascular/lung)",
            // "Composite structures",
        ],
        address: [
            "Room 243, Block IV,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "sroy[AT]am.iitd.ac.in",
        phone: "+91-11-2659-1220",
        page: "https://sites.google.com/view/sitilab-iitd/",
        image: "/faculty/sitikantha.png",
    },
    {
        name: "Manabendra Saharia",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Statistics and machine Learning, Data Assimilation",
            "Land surface/hydrologic modeling",
            "Hydrologic extremes, Flood and drought forecasting",
        ],
        address: [
            "Department of Civil Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "msaharia[AT]iitd.ac.in",
        phone: "+91-11-2659-1260",
        page: "https://hydrosenselab.github.io/",
        image: "/faculty/manabendra.jpg",
    },
    {
        name: "Smruti R. Sarangi",
        imgPos: "top",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Use of ML algorithms for temperature estimation and on-chip traffic prediction",
            "Design of AI/ML accelerators",
            "AI/ML algorithms on ultra-low power processors",
            "Architectures for stereo-vision (based on ML algorithms)",
        ],
        address: [
            "Room 215, SIT Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "srsarangi[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-7065",
        page: "https://www.cse.iitd.ac.in/~srsarangi/",
        image: "/faculty/smruti.jpg",
    },
    {
        name: "Rijurekha Sen",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Mobile and Embedded Systems (Hardware Architecture, OS, Sensing, Efficient Processing, Security)",
            "Computational Sustainability",
        ],
        address: ["Bharti 514,", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "riju[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-7385",
        page: "https://www.cse.iitd.ac.in/~rijurekha/",
        image: "/faculty/rijurekha.jpg",
    },
    {
        name: "Pradeep Shenoy",
        position: "Adjunct Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Cognitive Science",
            "Machine Learning",
            "Neuroscience",
        ],
        address: ["", ""],
        email: "pshenoy[AT]cs.washington.edu",
        phone: "",
        page: "https://research.google/people/106965/",
        image: "/faculty/pradeep.jpg",
    },
    {
        name: "Shaurya Shriyam",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Simulation Modelling",
            "Heuristics Optimization",
            "Multi-agent Planning and Reinforcement Learning",
        ],
        address: [
            "Room 258, Block III, Department of Mechanical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "shriyam[AT]iitd.ac.in",
        phone: "+91-11-2659-8428",
        page: "https://web.iitd.ac.in/~shriyam/index.html",
        image: "/faculty/shaurya.jpg",
    },
    {
        name: "Anup Singh",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Applications of Machine Learning in Healthcare",
            "Medical Image Processing",
            "Mathematical Modeling",
        ],
        address: [
            "Room No. 299, Block II, Center for Biomedical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "anupsm[AT]iitd.ac.in",
        phone: "+91-11-2659-1055",
        page: "https://web.iitd.ac.in/~anupsm/",
        image: "/faculty/anup.jpg",
    },
    {
        name: "Parag Singla",
        position: "Joint Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Machine Learning",
            "Social Network Analysis",
            "Artificial Intelligence",
        ],
        address: [
            "Room 413, Khosla School of IT, Department of Computer Science and Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "parags[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-6064",
        page: "https://www.cse.iitd.ac.in/~parags/index.html",
        image: "/faculty/parag.jpg",
    },
    {
        name: "D. Sundar",
        position: "Associate Faculty",
        // position: "Professor",
        research_areas: ["AI in Healthcare and Life Sciences"],
        address: ["XXXXXX", "IIT Delhi, Hauz Khas, New Delhi- 110016"],
        email: "sundar[AT]dbeb.iitd.ac.in",
        phone: "+91-11-2659-1066",
        page: "https://web.iitd.ac.in/~sundar/",
        image: "/faculty/sundar.png",
    },
    {
        name: "Manan Suri",
        imgPos: "top",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Specialized Hardware for Edge and Enterprise AI",
            "Neuromorphic Hardware",
            "Non Volatile Memory Technology",
            "Semiconductor Hardware Security",
            "Edge AI Applications",
        ],
        address: [
            "Room 115, Block II,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "manansuri[AT]ee.iitd.ac.in",
        phone: "+91-11-2659-1146",
        page: "https://web.iitd.ac.in/~manansuri/",
        image: "/faculty/manan.png",
    },
    {
        name: "Ashwini Vaidya",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: ["Computational linguistics", "Cognitive Science"],
        address: [
            "MS 623, IIT Delhi Campus,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "avaidya[AT]hss.iitd.ac.in",
        phone: "+91-11-2659-8405",
        page: "https://web.iitd.ac.in/~avaidya",
        image: "/faculty/ashwini.jpg",
    },
    {
        name: "Manik Varma",
        position: "Adjunct Faculty",
        // position: "Adjunct Faculty",
        research_areas: ["Machine Learning", "Computer Vision"],
        address: ["", ""],
        email: "manik[AT]cse.iitd.ac.in",
        phone: "+91-11-2659-XXXX",
        page: "http://manikvarma.org/",
        image: "/faculty/manik.jpg",
    },
    {
        name: "Ishaan Gupta",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Bio informatics",
            "Functional Genomics",
            "Genetics and AI",
        ],
        address: [
            "Room 325, Block I,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "ishaan[AT]iitd.ac.in",
        phone: "+91-11-2659-1008",
        page: "http://web.iitd.ac.in/~ishaan",
        image: "/faculty/ishaan.png",
    },
    {
        name: "Mani Mehra",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Wavelets methods for Partial Differential Equations",
            "Numerical Methods",
        ],
        address: [
            "Room: MZ161, Department of Mathematics,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "mmehra[AT]maths.iitd.ac.in",
        phone: "+91-11-2659-1487",
        page: "https://web.iitd.ac.in/~mmehra/",
        image: "/faculty/mani.jpg",
    },
    {
        name: "Tarak Karmakar",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Machine Learning (Artificial Intelligence in Chemistry)",
            "Development of Advanced Simulations Methods",
            "Molecular Dynamics & Enhanced Sampling Simulations",
        ],
        address: [
            "Department of Chemistry,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "tkarmakar[AT]chemistry.iitd.ac.in",
        phone: "+91-11-2659-8549",
        page: "https://chemistry.iitd.ac.in/faculty/karmakart.html",
        image: "/faculty/tarak.jpeg",
    },
    {
        name: "M. Ali Haider",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Machine Learning (Artificial Intelligence in Chemistry)",
            "Development of Advanced Simulations Methods",
        ],
        address: [
            "Room No. 112, Block-I, Department of Chemical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "haider[AT]iitd.ac.in",
        phone: "+91-11-2659-1016",
        page: "https://www.reclab.in/home",
        image: "/faculty/ali.png",
    },
    {
        name: "Lalan Kumar",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "EEG Source Localization",
            "Brain Computer Interface (BCI)",
            "Microphone Array Processing",
        ],
        address: [
            "Room No. 413C, Block II, Department of Electrical Engineering,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "lkumar[AT]ee.iitd.ac.in",
        phone: "+91-11-2659-7253",
        page: "https://web.iitd.ac.in/~lalank/",
        image: "/faculty/lalan.jpeg",
    },
    {
        name: "Gourab Ghatak",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Stochastic Geometry",
            "Millimeter-wave Communications",
            "5G Network Planning and Positioning in 5G",
        ],
        address: [
            "B-610 (R&D Block),",
            "IIIT Delhi, Okhla Industrial Estate, New Delhi- 110020",
        ],
        email: "gourab.ghatak[AT]iiitd.ac.in",
        phone: "+91-11-2690-7539",
        page: "https://www.gghatak.com/",
        image: "/faculty/gourab.jpg",
    },
    {
        name: "Tapan K Gandhi",
        position: "Associate Faculty",
        // position: "Associate Professor",
        research_areas: [
            "Computational Neuroscience",
            "Neuro-Inspired Engineering",
            "Biomedical Signal and Image Processing",
            "Machine Learning",
            "Assistive Technology"
        ],
        address: [
            "Room no: Block II/413(A),",
            "IIIT Delhi, Okhla Industrial Estate, New Delhi- 110020",
        ],
        email: "tgandhi@iitd.ac.in",
        phone: "+91 (011) 2659-1153",
        page: "https://tapankgandhi.com/",
        image: "/faculty/tapan.jpg",
    },
    {
        name: "Sandeep Sukumaran",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Climate modelling", 
            "Indian summer monsoon", 
            "climate change",
        ],
        address: [
            "Block VI, Room No. 312, Centre for Atmospheric Sciences,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "sandeep.sukumaran@cas.iitd.ac.in",
        phone: "(91)-11-2659-1387",
        page: "https://web.iitd.ac.in/~san81/",
        image: "/faculty/sandeep_sukumaran.jpg",
    },
    {
        name: "Prabhu Bahu",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Signal processing and communications",
            "Machine learning",
            "Nonlinear optimization",
            "Sparse parameter estimation aka compressed sensing",
            "Bioinformatics",
            "Big Data analysis",
            "Financial data modeling",
        ],
        address: [
            "Centre for Applied Research in Electronics,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "prabhubabu@care.iitd.ernet.in",
        phone: "+91-11-26597324",
        page: "https://care.iitd.ac.in/People/Faculty/Prabhubabu.html",
        image: "/faculty/prabhu_bahu.jpg",
    },
    {
        name: "Rohit Vaish",
        position: "Associate Faculty",
        // position: "Assistant Professor",
        research_areas: [
            "Computational social choice",
        ],
        address: [
            "Room 415, Department of Computer Science and Engineering, Bharti Building,",
            "IIT Delhi, Hauz Khas, New Delhi- 110016",
        ],
        email: "rvaish@iitd.ac.in",
        phone: "+91 (11) 2659 1295",
        page: "https://rohitvaish.in/",
        image: "/faculty/rohit_vaish.jpg",
    },
];

const mapdata = (data) => {
    return data.map((a, b) => {
        a.css = col[b % col.length];
        return a;
    });
};

export default mapdata(
    data.sort((a, b) => {
        if (a.name === "Mausam") {
            return -1;
        } else if (b.name === "Mausam") {
            return 1;
        } else {
            let o1 = a.name.split(" ");
            let o2 = b.name.split(" ");
            return o1[o1.length - 1].localeCompare(o2[o2.length - 1]);
        }
    })
);
